# Generated by Django 2.2.1 on 2019-05-12 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='unique_id',
            new_name='unique_ID',
        ),
    ]
