# Generated by Django 2.2.1 on 2019-05-12 08:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190512_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='unique_ID',
            field=models.CharField(auto_created=True, blank=True, default=uuid.uuid4, max_length=10, unique=True),
        ),
    ]
