# Generated by Django 2.2.1 on 2019-05-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190512_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='qty',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
        ),
    ]
